# Netlify 배포 설정 - LeadOn 1on1 Coach

[build]
  # 정적 사이트이므로 빌드 명령어 없음
  command = "echo 'Static PWA - No build needed'"
  
  # 배포할 디렉토리 (루트)
  publish = "."
  
  # 환경 변수
  [build.environment]
    NODE_VERSION = "18"

# 리다이렉트 및 리라이트 규칙
[[redirects]]
  # SPA 라우팅을 위한 fallback (해시 라우팅 사용하므로 불필요하지만 안전장치)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["visitor"]}

# PWA 관련 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    # 보안 헤더
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # HTTPS 강제 (프로덕션)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # CSP 헤더 (PWA용)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self';"

[[headers]]
  for = "/public/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400, s-maxage=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/public/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, s-maxage=2592000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 404 페이지 설정
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# Netlify 함수 (필요시 확장 가능)
# [functions]
#   directory = "netlify/functions"

# Netlify Edge Functions (필요시)
# [[edge_functions]]
#   function = "analytics"
#   path = "/*"

# 플러그인
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse"
    
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0.9

# 환경별 설정
[context.production.environment]
  NODE_ENV = "production"
  
[context.deploy-preview.environment]
  NODE_ENV = "preview"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"

# 개발 서버 설정
[dev]
  command = "python3 -m http.server 8000"
  port = 8000
  targetPort = 8000
  publish = "."
